-- AlterTable
ALTER TABLE "Team"
  ADD COLUMN IF NOT EXISTS "shieldUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "footballType" INTEGER NOT NULL DEFAULT 11,
  ADD COLUMN IF NOT EXISTS "formation" TEXT NOT NULL DEFAULT '4-4-2';
